# Generated by Django 6.0.3 on 2026-04-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongo', 'MongoDB'), ('clickhouse', 'ClickHouse')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
            ],
        ),
    ]
