# Generated by Django 6.0.3 on 2026-04-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_user_storedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
