# Generated by Django 6.0.3 on 2026-04-13 12:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_alter_storedfile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracteddata',
            options={'verbose_name': 'Extracted Data', 'verbose_name_plural': 'Extracted Data'},
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedfile',
            name='extracted_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_file', to='connector.extracteddata'),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='format_type',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=10),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
