# Generated by Django 6.0.3 on 2026-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_databaseconnection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedfile',
            old_name='created_at',
            new_name='extracted_at',
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='updated_at',
            new_name='last_modified_at',
        ),
        migrations.AddField(
            model_name='storedfile',
            name='base_filename',
            field=models.CharField(blank=True, help_text='Base filename without timestamp', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='connection_name',
            field=models.CharField(blank=True, help_text='Database connection name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='table_name',
            field=models.CharField(blank=True, help_text='Original table name', max_length=255, null=True),
        ),
    ]
