# Generated by Django 6.0.4 on 2026-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_rename_created_at_storedfile_extracted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
